# Generated by Django 3.1.2 on 2020-10-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20201014_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='caratula',
            field=models.ImageField(default='undefined.png', upload_to='libros'),
        ),
    ]
