# Generated by Django 3.1.2 on 2020-11-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_libro_caratula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='fecha_fall',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha fall'),
        ),
    ]
