# Generated by Django 3.1.2 on 2020-11-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20201126_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='fecha_fall',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha defunción'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento'),
        ),
    ]
